### ISSUE TITLE
The website is not secure.

### ISSUE THREAD

**Issue by QinxinTian** [RyanDanielOMara/nbai#140]
<img width="584" alt="2017-11-06 7 11 17" src="https://user-images.githubusercontent.com/25886116/32440570-bdcc9248-c2c1-11e7-8f74-e3d9cc8826ac.png">
If it is secure, the left hand side of the address should be green.

**Comment by mattalexhoward** [comment]
Yes you are correct. We did not use https because we don't have any user
information or any data that would be harmful if an attacker deployed a
sniffer attack.

**Comment by jcgoodru** [comment]
I don't think our site needs to be secure, since we don't handle user info.  The only thing a MITM can intercept is what players a particular site user is searching for.  Also there's added latency with https traffic.

espn.com also uses http (probably fort he same reasons as us).
