### ISSUE TITLE
Incorrect Career Stats

### ISSUE THREAD

**Issue by RyanDanielOMara** [RyanDanielOMara/nbai#183]
The RPG and AST career stats are currently incorrect.

**Comment by jcgoodru** [comment]
These stats should be reflective of the data in the database.  You can verify the correctness by looking at someone who joined the league anytime after the oldest year you've backfilled.

Ex: if you backfilled from 2007 till today, then anyone drafted in or after 2007 will have correct career stats but people from before there (LeBron, etc) won't 

Did you check this?

**Comment by RyanDanielOMara** [comment]
@jcgoodru I should have specified, the stats themselves are correct, the ones being displayed are the labeled incorrectly.  I'm fixing this in a pull request in the next minute or two.

**Comment by jcgoodru** [comment]
Ah, cool
