### ISSUE TITLE
Create MongoDB Documents for storing Player info and Game info

### ISSUE THREAD

**Issue by akotler** [RyanDanielOMara/nbai#23]
Documents needed to be created:

BaseObject:

- creates time stamp
- makes it so fields are called differently then MongoKit's default.

PlayerObject:
- player id
- personal info
- games played (dictionary)

TeamObject:
-team id
-team name
- roster (avg 14 players per team)
- games played (dictionary)

TeamGameObject:

- game id
-game info

PlayerGameObject:
- game id
- player id
- stats of player for game

**Comment by jcgoodru** [comment]
Resolved
