### ISSUE TITLE
Fantasy points calculator

### ISSUE THREAD

**Issue by akotler** [RyanDanielOMara/nbai#34]
Need a function that takes in a players stats for a given game and outputs the calculation of their fantasy points for that given game based on espn's breakdown of points awarded per stat.

fantasy__points_calculator(pts,blk,stl,ast,rb,fgm,fga,ft,fta,to){
        //return amount of fantasy points earned
}

//espn's awarded points can be seen in the parentheses
//pts = points scored (+1 pt)
//blk = blocks (+1 pt)
//stl = steals (+1 pt)
//ast = assists (+1 pt)
//rb = rebounds (+1 pt)
//fgm = field goals made (+1 pt)
//fga = field goals attempted (-1 pt)
//ft = free throws (+1 pt)
//fta = free throws attempted (-1 pt)
//to = to (-1 pt)

**Comment by jcgoodru** [comment]
We'll need to update the current calculator to pull from the Player collection and edit those values
