### ISSUE TITLE
migrate server

### ISSUE THREAD

**Issue by mattalexhoward** [RyanDanielOMara/nbai#41]
Moving server to another computer to gain access to more computing power.

**Comment by mattalexhoward** [comment]
Successfully moved web server. Working on autonomous start up.

**Comment by mattalexhoward** [comment]
Successfully have autonomous start up. Enabling SSL redirect back to non-ssl site.

**Comment by mattalexhoward** [comment]
SSL redirect done.

**Comment by mattalexhoward** [comment]
Server fully migrated. SSH keys distributed to team.

**Comment by jcgoodru** [comment]
I don't think we should all have access to this host.  This host shouldn't contain anything not-in the master branch, and if we follow the correct git procedures then any changes we need to make will get to master when needed

**Comment by jcgoodru** [comment]
I can't think of any scenarios where any of us should be connecting to this machine.  Any changes we need to make should be scriptable

**Comment by mattalexhoward** [comment]
So all development will happen on the devs local machine?

**Comment by jcgoodru** [comment]
Yes.  We can leave a script running on this production host.  This script will look for pushes to master, and whenever it sees a new one, it'll pull from master and restart the server
