### ISSUE TITLE
Implement New Table Design

### ISSUE THREAD

**Issue by RyanDanielOMara** [RyanDanielOMara/nbai#44]
- Redesign the table to fit the structure of the graphical prototype.

- Update the colors/overall design to match the graphical prototype.

![nbai-prototype](https://user-images.githubusercontent.com/22532260/31251009-93a9f98c-a9ea-11e7-98a4-539083151649.png)

**Comment by jcgoodru** [comment]
@RyanDanielOMara This is done, right?

Or no?

**Comment by RyanDanielOMara** [comment]
Correct, done in #51 .  Closed.
