### ISSUE TITLE
Add button functionality to the web page

### ISSUE THREAD

**Issue by Jeffreywye** [RyanDanielOMara/nbai#68]
Use html, javascript, and python to send a signal to the server when a button is pressed.

**Comment by jcgoodru** [comment]
@Jeffreywye : 

I think @mattalexhoward wants to work on this.  He mentioned earlier that he wants to handle the HTML/CSS related tasks.  You two should sync up and decide how to work together on this.  Perhaps one of you can take the HTML/CSS and the other can handle the Javascript/AJAX calls

**Comment by jcgoodru** [comment]
Please do not put buttons on anything
