### ISSUE TITLE
Players Page

### ISSUE THREAD

**Issue by RyanDanielOMara** [RyanDanielOMara/nbai#72]
- Determine what info we want to display:
    - Player picture, basic bio info
    - Most recent x games with stats
    - Another table of all games he's forecast to play in
    - Previous predictions, accuracy of predictions

- Create mockup
- Implement design

**Comment by jcgoodru** [comment]
Copied from #32:

**Post MVP** feature: add a "Player" page, contents TBD.  Some ideas for what it can contain are:

* Picture
* Bio and "Physical" Attributes
    * Name, age, school, years exp, current team, etc...
* Career Statistics
    * PPG, minutes per game, etc...
* Most Recent Statistics
    * Career Statistics from the most recent XX games
* Game Log
    * Table (?) of games from this season (including XX upcoming games)
    * Maybe a summary of last season, if "today's" date is early in the current season
* Stats about his predictions
    * Is he usually under/overvalued (when comparing his ESPN projection to his IRL performance)?
    * Maybe some graphs about his performance (Relative to what?  League averages?)
