### ISSUE TITLE
Design a table in player_page.html

### ISSUE THREAD

**Issue by Jeffreywye** [RyanDanielOMara/nbai#79]
If there's already a table in player_page.html then go here:  #82

Either use jinja templating to design the table or design a static table. In the table show the player's previous predicted over/under value and show our predicted fantasy scores.

**Comment by gjbunyea** [comment]
Can I have some more details on this? 
You've already got this table:
![image](https://user-images.githubusercontent.com/18299544/32294303-1a403dbc-bf1c-11e7-8a16-11a5ef0b0bec.png)

Do you want something different? Though this table isn't populating - is that what I'm supposed to fix?

**Comment by Jeffreywye** [comment]
Do u want to meet up tmrw to discuss your problem? (Msg your response on ryver).

**Comment by gjbunyea** [comment]
![image](https://user-images.githubusercontent.com/18299544/32299717-ff0812b6-bf2c-11e7-9f39-58a16d3c8051.png)
