### ISSUE TITLE
Add sorting functionality to table in player page

### ISSUE THREAD

**Issue by akotler** [RyanDanielOMara/nbai#82]
if there is no table available before hand then design a static table in player page as a placeholder #79

Use javascript to create a method in players_page.js that sorts the table by clicking on the table headers.
This method should take in the index of the column to be sorted by as an input.

Design a table in player_page.html #79

**Comment by noahpoz** [comment]
I'm trying to view the player_page.html in the browser. According to the documentation, I need to access it through the route localhost:5000/players/[playerid]. I queried to the database and retrieved an _id and tried to go to this route, but it isn't working. Maybe I'm not inserting the ID correctly? Is the functionality in place to route to this page based on playerID?

**Comment by noahpoz** [comment]
Is there a time today that you'd be available for a Skype call?

**Comment by akotler** [comment]
I believe you are retrieving the wrong field. There is a player_id field with the player's id you are querying.  This is why you aren't having success.

**Comment by akotler** [comment]
If you browse to nbai/src/database/tables/league/player.py you will see the fields that are part of this table one being player_id

**Comment by noahpoz** [comment]
So I'm thinking of branching off of Greg's PR #128. I'll just populate the table with some dummy data and make the table sortable using Javascript. Would that be alright?

By the way, I was able to get the page to display. Thanks for your help there.

**Comment by RyanDanielOMara** [comment]
Yes @noahpoz that would be ideal.  I'll have a look at you're updated code in your pull request.  Thanks!

**Comment by jcgoodru** [comment]
This is done right?  Reopen if not
